# Generated by Django 4.1.4 on 2022-12-26 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diablo3citadel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='characterClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('skillCategories', models.JSONField()),
                ('skills', models.JSONField()),
                ('passive', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.JSONField()),
                ('runes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('tooltipParams', models.CharField(max_length=200)),
                ('requiredLevel', models.IntegerField()),
                ('stackSizeMax', models.IntegerField()),
                ('accountBound', models.BooleanField()),
                ('flavorText', models.TextField()),
                ('flavorTextHtml', models.TextField()),
                ('typeName', models.CharField(max_length=100)),
                ('type', models.JSONField()),
                ('damage', models.TextField()),
                ('dps', models.CharField(max_length=100)),
                ('damageHtml', models.TextField()),
                ('color', models.CharField(max_length=100)),
                ('isSeasonRequiredToDrop', models.BooleanField()),
                ('seasonRequiredToDrop', models.IntegerField()),
                ('slots', models.JSONField()),
                ('attributes', models.JSONField()),
                ('randomAffixes', models.JSONField()),
                ('setItems', models.JSONField()),
                ('itemTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diablo3citadel.itemtype')),
            ],
        ),
    ]
