# Generated by Django 4.1.4 on 2022-12-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diablo3citadel', '0005_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='flavorText',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='item',
            name='flavorTextHtml',
            field=models.TextField(default='0'),
        ),
    ]
