# Generated by Django 4.1.4 on 2022-12-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diablo3citadel', '0006_alter_item_flavortext_alter_item_flavortexthtml'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
